pipeline {
    agent { docker { image 'maven: 3.3.3'}}
    stages {
        // 빌드시
        stage('Build') {
            steps {
                sh 'mvn --version'
                sh 'echo "Hello World"'
                sh '''
                    echo "Multiline shell steps works too"
                    ls -lah
                '''
            }
        }
        // 배포시
        stage('Deploy') {
            steps {
                // 3번 시도함
               // retry(3) {
               //     echo 'enter retry'

                    /* dir('shellScripts'){
                            sh 'sudo ./flakey-deploy.sh'
                    } */
               // }
                // 3분이 지나면 timeout
                // timeout(time: 3, unit: 'MINUTES') {
                //    echo 'enter timeout'

                    /* dir('shellScripts'){
                            sh 'sudo ./health-check.sh'
                        } */

                // }
                timeout(time: 3, unit: 'MINUTES') {
                    retry(5) {
                        echo 'timeout and retry test'
                    }
                }

            }
        }

       /* stage('Test') {
            steps {
                sh 'echo "Fail '
            }
        } */
    } // stages end
} // pipeline end