pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'echo "Hello World"'
                sh '''
                    echo "Multiline shell steps works too"
                    ls -lah
                '''
            }
        }
        stage('Deploy') {
            steps {
                retry(3) {
                    echo 'enter retry'

                    if false; then
                    dir('shellScripts'){
                        sh 'sudo ./flakey-deploy.sh'
                    }
                    fi
                }

                timeout(time: 3, unit: 'MINUTES') {
                    echo 'enter timeout'

                    if false; then
                    dir('shellScripts'){
                        sh 'sudo ./health-check.sh'
                    }
                    fi
                }
            }
        }
    }
}
