pipeline {
    agent any
    stages {
        // 빌드시
        stage('Build') {
            steps {
                sh 'echo "Hello World"'
                sh '''
                    echo "Multiline shell steps works too"
                    ls -lah
                '''
            }
        }
        // 배포시
        stage('Deploy') {
            steps {
                // 3번 시도함
                retry(3) {
                    echo 'enter retry'

                    if false; then
                    dir('shellScripts'){
                        sh 'sudo ./flakey-deploy.sh'
                    }
                    fi
                }
                // 3분 단위로 타임아웃 체크
                timeout(time: 3, unit: 'MINUTES') {
                    echo 'enter timeout'

                    if false; then
                    dir('shellScripts'){
                        sh 'sudo ./health-check.sh'
                    }
                    fi
                }
            }
        }
    }
}
